//
// File generated by /root/bin/rootcint at Wed Jan 29 18:29:53 2020

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME BHL6Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "BHL6Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void TMCgenBHL6_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TMCgenBHL6(void *p = 0);
   static void *newArray_TMCgenBHL6(Long_t size, void *p);
   static void delete_TMCgenBHL6(void *p);
   static void deleteArray_TMCgenBHL6(void *p);
   static void destruct_TMCgenBHL6(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::TMCgenBHL6*)
   {
      ::TMCgenBHL6 *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TMCgenBHL6 >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TMCgenBHL6", ::TMCgenBHL6::Class_Version(), "./TMCgenBHL6.h", 87,
                  typeid(::TMCgenBHL6), ::ROOT::DefineBehavior(ptr, ptr),
                  &::TMCgenBHL6::Dictionary, isa_proxy, 4,
                  sizeof(::TMCgenBHL6) );
      instance.SetNew(&new_TMCgenBHL6);
      instance.SetNewArray(&newArray_TMCgenBHL6);
      instance.SetDelete(&delete_TMCgenBHL6);
      instance.SetDeleteArray(&deleteArray_TMCgenBHL6);
      instance.SetDestructor(&destruct_TMCgenBHL6);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::TMCgenBHL6*)
   {
      return GenerateInitInstanceLocal((::TMCgenBHL6*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TMCgenBHL6*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr TMCgenBHL6::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *TMCgenBHL6::Class_Name()
{
   return "TMCgenBHL6";
}

//______________________________________________________________________________
const char *TMCgenBHL6::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::TMCgenBHL6*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TMCgenBHL6::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::TMCgenBHL6*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TMCgenBHL6::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::TMCgenBHL6*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TMCgenBHL6::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::TMCgenBHL6*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void TMCgenBHL6::Streamer(TBuffer &R__b)
{
   // Stream an object of class TMCgenBHL6.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(TMCgenBHL6::Class(),this);
   } else {
      R__b.WriteClassBuffer(TMCgenBHL6::Class(),this);
   }
}

//______________________________________________________________________________
void TMCgenBHL6::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TMCgenBHL6.
      TClass *R__cl = ::TMCgenBHL6::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "f_Name[64]", f_Name);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "f_Version", &f_Version);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "f_Date[40]", f_Date);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*f_RNgen", &f_RNgen);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*f_TMCgen_NORMA", &f_TMCgen_NORMA);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "f_IsInitialized", &f_IsInitialized);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*f_GenFile", &f_GenFile);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*f_HstFile", &f_HstFile);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*f_Out", &f_Out);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "f_NevGen", &f_NevGen);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_NevTot", &m_NevTot);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_EvenCounter", &m_EvenCounter);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_jmax", &m_jmax);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_ypar[10001]", m_ypar);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_npar[10001]", m_npar);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_XsNormPb", &m_XsNormPb);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_XsErroPb", &m_XsErroPb);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_ijkl_new", &m_ijkl_new);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_ntot_new", &m_ntot_new);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_ntot2_new", &m_ntot2_new);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_out", &m_out);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_KeyGen", &m_KeyGen);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_KeyRem", &m_KeyRem);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_KeyWgt", &m_KeyWgt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_KeyRnd", &m_KeyRnd);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_KeyZet", &m_KeyZet);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_KeyUpd", &m_KeyUpd);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_KeyMod", &m_KeyMod);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_KeyPia", &m_KeyPia);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_CMSENE", &m_CMSENE);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_angmin", &m_angmin);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_angmax", &m_angmax);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_TRMIN", &m_TRMIN);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_TRMAX", &m_TRMAX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_EPSCM", &m_EPSCM);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_VMAXG", &m_VMAXG);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_TMCgenBHL6(void *p) {
      return  p ? new(p) ::TMCgenBHL6 : new ::TMCgenBHL6;
   }
   static void *newArray_TMCgenBHL6(Long_t nElements, void *p) {
      return p ? new(p) ::TMCgenBHL6[nElements] : new ::TMCgenBHL6[nElements];
   }
   // Wrapper around operator delete
   static void delete_TMCgenBHL6(void *p) {
      delete ((::TMCgenBHL6*)p);
   }
   static void deleteArray_TMCgenBHL6(void *p) {
      delete [] ((::TMCgenBHL6*)p);
   }
   static void destruct_TMCgenBHL6(void *p) {
      typedef ::TMCgenBHL6 current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::TMCgenBHL6

/********************************************************
* BHL6Dict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableBHL6Dict();

extern "C" void G__set_cpp_environmentBHL6Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("TMCgenBHL6.h");
  G__cpp_reset_tagtableBHL6Dict();
}
#include <new>
extern "C" int G__cpp_dllrevBHL6Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TMCgenBHL6 */
static int G__BHL6Dict_329_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TMCgenBHL6* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TMCgenBHL6[n];
     } else {
       p = new((void*) gvp) TMCgenBHL6[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TMCgenBHL6;
     } else {
       p = new((void*) gvp) TMCgenBHL6;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BHL6DictLN_TMCgenBHL6));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TMCgenBHL6* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new TMCgenBHL6((const char*) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) TMCgenBHL6((const char*) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BHL6DictLN_TMCgenBHL6));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMCgenBHL6*) G__getstructoffset())->Initialize((TRandom*) G__int(libp->para[0]), (ofstream*) G__int(libp->para[1])
, (TH1D*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMCgenBHL6*) G__getstructoffset())->ReInitialize((ofstream*) G__int(libp->para[0]), (TH1D*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMCgenBHL6*) G__getstructoffset())->Finalize();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMCgenBHL6*) G__getstructoffset())->Generate();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TMCgenBHL6*) G__getstructoffset())->sqr((const double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TMCgenBHL6*) G__getstructoffset())->Min(*(int*) G__Intref(&libp->para[0]), *(int*) G__Intref(&libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMCgenBHL6*) G__getstructoffset())->StopM((char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const TMCgenBHL6*) G__getstructoffset())->GetIsNewRun());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMCgenBHL6*) G__getstructoffset())->GetPhoton1((const int) G__int(libp->para[0]), *(TLorentzVector*) libp->para[1].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMCgenBHL6*) G__getstructoffset())->GetWt(*(double*) G__Doubleref(&libp->para[0]), *(double*) G__Doubleref(&libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMCgenBHL6*) G__getstructoffset())->GetBeams(*(TLorentzVector*) libp->para[0].ref, *(TLorentzVector*) libp->para[1].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMCgenBHL6*) G__getstructoffset())->GetFermions(*(TLorentzVector*) libp->para[0].ref, *(TLorentzVector*) libp->para[1].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMCgenBHL6*) G__getstructoffset())->GetPrimaNorma(*(int*) G__Intref(&libp->para[0]), *(double*) G__Doubleref(&libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMCgenBHL6*) G__getstructoffset())->GetNphot(*(int*) G__Intref(&libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TMCgenBHL6*) G__getstructoffset())->GetWtAlter((const int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMCgenBHL6*) G__getstructoffset())->Print1();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMCgenBHL6*) G__getstructoffset())->SetInOut(*(int*) G__Intref(&libp->para[0]), *(int*) G__Intref(&libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMCgenBHL6*) G__getstructoffset())->ReModel(*(double*) G__Doubleref(&libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TMCgenBHL6*) G__getstructoffset())->BornBhl(*(double*) G__Doubleref(&libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TMCgenBHL6*) G__getstructoffset())->BornBhl2((double) G__double(libp->para[0]), (double) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMCgenBHL6*) G__getstructoffset())->SetKeyPia(*(int*) G__Intref(&libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMCgenBHL6*) G__getstructoffset())->SetKeyZet(*(int*) G__Intref(&libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMCgenBHL6*) G__getstructoffset())->SetKeyPib(*(int*) G__Intref(&libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMCgenBHL6*) G__getstructoffset())->SetKeyMod(*(int*) G__Intref(&libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TMCgenBHL6::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TMCgenBHL6::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TMCgenBHL6::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TMCgenBHL6::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMCgenBHL6*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TMCgenBHL6::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TMCgenBHL6::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TMCgenBHL6::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BHL6Dict_329_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TMCgenBHL6::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__BHL6Dict_329_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TMCgenBHL6* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TMCgenBHL6(*(TMCgenBHL6*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BHL6DictLN_TMCgenBHL6));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TMCgenBHL6 G__TTMCgenBHL6;
static int G__BHL6Dict_329_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TMCgenBHL6*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TMCgenBHL6*) (soff+(sizeof(TMCgenBHL6)*i)))->~G__TTMCgenBHL6();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TMCgenBHL6*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TMCgenBHL6*) (soff))->~G__TTMCgenBHL6();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__BHL6Dict_329_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TMCgenBHL6* dest = (TMCgenBHL6*) G__getstructoffset();
   *dest = *(TMCgenBHL6*) libp->para[0].ref;
   const TMCgenBHL6& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TMCgenBHL6 */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncBHL6Dict {
 public:
  G__Sizep2memfuncBHL6Dict(): p(&G__Sizep2memfuncBHL6Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncBHL6Dict::*p)();
};

size_t G__get_sizep2memfuncBHL6Dict()
{
  G__Sizep2memfuncBHL6Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceBHL6Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__BHL6DictLN_TMCgenBHL6))) {
     TMCgenBHL6 *G__Lderived;
     G__Lderived=(TMCgenBHL6*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__BHL6DictLN_TMCgenBHL6),G__get_linked_tagnum(&G__BHL6DictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableBHL6Dict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__BHL6DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BHL6DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BHL6DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BHL6DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BHL6DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__BHL6DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BHL6DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BHL6DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BHL6DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BHL6DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__BHL6DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__BHL6DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__BHL6DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__BHL6DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__BHL6DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__BHL6DictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__BHL6DictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__BHL6DictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__BHL6DictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__BHL6DictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__BHL6DictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__BHL6DictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__BHL6DictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__BHL6DictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__BHL6DictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__BHL6DictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__BHL6DictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__BHL6DictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__BHL6DictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__BHL6DictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__BHL6DictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__BHL6DictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__BHL6DictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__BHL6DictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__BHL6DictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__BHL6DictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TMCgenBHL6 */
static void G__setup_memvarTMCgenBHL6(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__BHL6DictLN_TMCgenBHL6));
   { TMCgenBHL6 *p; p=(TMCgenBHL6*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->f_Name)-(long)(p)),99,0,0,-1,-1,-1,1,"f_Name[64]=",0,"Name of a give instance of the class");
   G__memvar_setup((void*)((long)(&p->f_Version)-(long)(p)),102,0,0,-1,-1,-1,1,"f_Version=",0,"Actual VERSION of the program");
   G__memvar_setup((void*)((long)(&p->f_Date)-(long)(p)),99,0,0,-1,-1,-1,1,"f_Date[40]=",0,"Release DATE of the program");
   G__memvar_setup((void*)((long)(&p->f_RNgen)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BHL6DictLN_TRandom),-1,-1,1,"f_RNgen=",0,"External RN event generator");
   G__memvar_setup((void*)((long)(&p->f_TMCgen_NORMA)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BHL6DictLN_TH1D),-1,-1,1,"f_TMCgen_NORMA=",0,"! special histo keeping overall normalization");
   G__memvar_setup((void*)((long)(&p->f_IsInitialized)-(long)(p)),105,0,0,-1,-1,-1,1,"f_IsInitialized=",0,"prevents repeating initialization");
   G__memvar_setup((void*)((long)(&p->f_GenFile)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BHL6DictLN_TFile),-1,-1,1,"f_GenFile=",0,"! ROOT DiskFile with MC generator object and data");
   G__memvar_setup((void*)((long)(&p->f_HstFile)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BHL6DictLN_TFile),-1,-1,1,"f_HstFile=",0,"! ROOT DiskFile with all histos");
   G__memvar_setup((void*)((long)(&p->f_Out)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__BHL6DictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR),G__defined_typename("ofstream"),-1,1,"f_Out=",0,"! External Logfile for messages");
   G__memvar_setup((void*)((long)(&p->f_NevGen)-(long)(p)),100,0,0,-1,-1,-1,1,"f_NevGen=",0,"event serial number");
   G__memvar_setup((void*)((long)(&p->m_NevTot)-(long)(p)),108,0,0,-1,-1,-1,1,"m_NevTot=",0,"total numer of events to be generated");
   G__memvar_setup((void*)((long)(&p->m_EvenCounter)-(long)(p)),108,0,0,-1,-1,-1,1,"m_EvenCounter=",0,"event serial counter");
   G__memvar_setup((void*)((long)(&p->m_jmax)-(long)(p)),105,0,0,-1,-1,-1,1,"m_jmax=",0,"lenght of ymar");
   G__memvar_setup((void*)((long)(&p->m_ypar)-(long)(p)),100,0,0,-1,-1,-1,1,"m_ypar[10001]=",0,"xpar input params for BHLUMI4");
   G__memvar_setup((void*)((long)(&p->m_npar)-(long)(p)),105,0,0,-1,-1,-1,1,"m_npar[10001]=",0,"npar input params for BHLUMI4");
   G__memvar_setup((void*)((long)(&p->m_XsNormPb)-(long)(p)),100,0,0,-1,-1,-1,1,"m_XsNormPb=",0,"normalization");
   G__memvar_setup((void*)((long)(&p->m_XsErroPb)-(long)(p)),100,0,0,-1,-1,-1,1,"m_XsErroPb=",0,"normalization");
   G__memvar_setup((void*)((long)(&p->m_ijkl_new)-(long)(p)),105,0,0,-1,-1,-1,1,"m_ijkl_new=",0,"= 54217137;");
   G__memvar_setup((void*)((long)(&p->m_ntot_new)-(long)(p)),105,0,0,-1,-1,-1,1,"m_ntot_new=",0,"= 0;");
   G__memvar_setup((void*)((long)(&p->m_ntot2_new)-(long)(p)),105,0,0,-1,-1,-1,1,"m_ntot2_new=",0,"= 0;");
   G__memvar_setup((void*)((long)(&p->m_out)-(long)(p)),108,0,0,-1,-1,-1,1,"m_out=",0,"output unit number");
   G__memvar_setup((void*)((long)(&p->m_KeyGen)-(long)(p)),105,0,0,-1,-1,-1,1,"m_KeyGen=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->m_KeyRem)-(long)(p)),105,0,0,-1,-1,-1,1,"m_KeyRem=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->m_KeyWgt)-(long)(p)),105,0,0,-1,-1,-1,1,"m_KeyWgt=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->m_KeyRnd)-(long)(p)),105,0,0,-1,-1,-1,1,"m_KeyRnd=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->m_KeyZet)-(long)(p)),105,0,0,-1,-1,-1,1,"m_KeyZet=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->m_KeyUpd)-(long)(p)),105,0,0,-1,-1,-1,1,"m_KeyUpd=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->m_KeyMod)-(long)(p)),105,0,0,-1,-1,-1,1,"m_KeyMod=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->m_KeyPia)-(long)(p)),105,0,0,-1,-1,-1,1,"m_KeyPia=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->m_CMSENE)-(long)(p)),100,0,0,-1,-1,-1,1,"m_CMSENE=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->m_angmin)-(long)(p)),100,0,0,-1,-1,-1,1,"m_angmin=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->m_angmax)-(long)(p)),100,0,0,-1,-1,-1,1,"m_angmax=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->m_TRMIN)-(long)(p)),100,0,0,-1,-1,-1,1,"m_TRMIN=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->m_TRMAX)-(long)(p)),100,0,0,-1,-1,-1,1,"m_TRMAX=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->m_EPSCM)-(long)(p)),100,0,0,-1,-1,-1,1,"m_EPSCM=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->m_VMAXG)-(long)(p)),100,0,0,-1,-1,-1,1,"m_VMAXG=",0,"= 0.9999e0, VMAXG   v_max generation");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__BHL6DictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarBHL6Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTMCgenBHL6(void) {
   /* TMCgenBHL6 */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__BHL6DictLN_TMCgenBHL6));
   G__memfunc_setup("TMCgenBHL6",810,G__BHL6Dict_329_0_1, 105, G__get_linked_tagnum(&G__BHL6DictLN_TMCgenBHL6), -1, 0, 0, 1, 1, 0, "", "explicit default constructor for streamer", (void*) NULL, 0);
   G__memfunc_setup("TMCgenBHL6",810,G__BHL6Dict_329_0_2, 105, G__get_linked_tagnum(&G__BHL6DictLN_TMCgenBHL6), -1, 0, 1, 1, 1, 0, "C - - 10 - -", "user constructor", (void*) NULL, 0);
   G__memfunc_setup("Initialize",1042,G__BHL6Dict_329_0_3, 121, -1, -1, 0, 3, 1, 1, 0, 
"U 'TRandom' - 0 - - U 'basic_ofstream<char,char_traits<char> >' 'ofstream' 0 - - "
"U 'TH1D' - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReInitialize",1225,G__BHL6Dict_329_0_4, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'basic_ofstream<char,char_traits<char> >' 'ofstream' 0 - - U 'TH1D' - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Finalize",818,G__BHL6Dict_329_0_5, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Generate",811,G__BHL6Dict_329_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("sqr",342,G__BHL6Dict_329_0_7, 100, -1, -1, 0, 1, 1, 1, 0, "d - - 10 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Min",292,G__BHL6Dict_329_0_8, 105, -1, -1, 0, 2, 1, 1, 0, 
"i - - 1 - i i - - 1 - j", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("StopM",499,G__BHL6Dict_329_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 0 - message", "Error message", (void*) NULL, 0);
   G__memfunc_setup("GetIsNewRun",1083,G__BHL6Dict_329_0_10, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPhoton1",969,G__BHL6Dict_329_0_11, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 10 - iphot u 'TLorentzVector' - 1 - phot", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetWt",491,G__BHL6Dict_329_0_12, 121, -1, -1, 0, 2, 1, 1, 0, 
"d - - 1 - - d - - 1 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetBeams",776,G__BHL6Dict_329_0_13, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TLorentzVector' - 1 - - u 'TLorentzVector' - 1 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetFermions",1123,G__BHL6Dict_329_0_14, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TLorentzVector' - 1 - - u 'TLorentzVector' - 1 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPrimaNorma",1302,G__BHL6Dict_329_0_15, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 1 - - d - - 1 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNphot",809,G__BHL6Dict_329_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 1 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetWtAlter",995,G__BHL6Dict_329_0_17, 100, -1, -1, 0, 1, 1, 1, 0, "i - - 10 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Print1",574,G__BHL6Dict_329_0_18, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetInOut",795,G__BHL6Dict_329_0_19, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 11 - - i - - 11 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReModel",680,G__BHL6Dict_329_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 11 - WtMain", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BornBhl",679,G__BHL6Dict_329_0_21, 100, -1, -1, 0, 3, 1, 1, 0, 
"d - - 1 - cmsene d - - 0 - thmin "
"d - - 0 - thmax", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BornBhl2",729,G__BHL6Dict_329_0_22, 100, -1, -1, 0, 2, 1, 1, 0, 
"d - - 0 - thmin d - - 0 - thmax", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetKeyPia",879,G__BHL6Dict_329_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 11 - KeyPia", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetKeyZet",904,G__BHL6Dict_329_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 11 - KeyZet", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetKeyPib",880,G__BHL6Dict_329_0_25, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 11 - KeyPib", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetKeyMod",885,G__BHL6Dict_329_0_26, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 11 - KeyMod", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__BHL6Dict_329_0_27, 85, G__get_linked_tagnum(&G__BHL6DictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TMCgenBHL6::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__BHL6Dict_329_0_28, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TMCgenBHL6::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__BHL6Dict_329_0_29, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TMCgenBHL6::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__BHL6Dict_329_0_30, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TMCgenBHL6::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__BHL6DictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__BHL6Dict_329_0_34, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__BHL6Dict_329_0_35, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TMCgenBHL6::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__BHL6Dict_329_0_36, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TMCgenBHL6::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__BHL6Dict_329_0_37, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TMCgenBHL6::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__BHL6Dict_329_0_38, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TMCgenBHL6::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TMCgenBHL6", 810, G__BHL6Dict_329_0_39, (int) ('i'), G__get_linked_tagnum(&G__BHL6DictLN_TMCgenBHL6), -1, 0, 1, 1, 1, 0, "u 'TMCgenBHL6' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TMCgenBHL6", 936, G__BHL6Dict_329_0_40, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__BHL6Dict_329_0_41, (int) ('u'), G__get_linked_tagnum(&G__BHL6DictLN_TMCgenBHL6), -1, 1, 1, 1, 1, 0, "u 'TMCgenBHL6' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncBHL6Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalBHL6Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcBHL6Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__BHL6DictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR = { "basic_ofstream<char,char_traits<char> >" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_TRandom = { "TRandom" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__BHL6DictLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_TH1D = { "TH1D" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_TLorentzVector = { "TLorentzVector" , 99 , -1 };
G__linked_taginfo G__BHL6DictLN_TMCgenBHL6 = { "TMCgenBHL6" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableBHL6Dict() {
  G__BHL6DictLN_TClass.tagnum = -1 ;
  G__BHL6DictLN_TBuffer.tagnum = -1 ;
  G__BHL6DictLN_TMemberInspector.tagnum = -1 ;
  G__BHL6DictLN_TObject.tagnum = -1 ;
  G__BHL6DictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR.tagnum = -1 ;
  G__BHL6DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__BHL6DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BHL6DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__BHL6DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BHL6DictLN_TRandom.tagnum = -1 ;
  G__BHL6DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__BHL6DictLN_TFile.tagnum = -1 ;
  G__BHL6DictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__BHL6DictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__BHL6DictLN_TH1D.tagnum = -1 ;
  G__BHL6DictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__BHL6DictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__BHL6DictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__BHL6DictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__BHL6DictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__BHL6DictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__BHL6DictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__BHL6DictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__BHL6DictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__BHL6DictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__BHL6DictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__BHL6DictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__BHL6DictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__BHL6DictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__BHL6DictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__BHL6DictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__BHL6DictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__BHL6DictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__BHL6DictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__BHL6DictLN_TLorentzVector.tagnum = -1 ;
  G__BHL6DictLN_TMCgenBHL6.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableBHL6Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_TClass);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_TObject);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_TRandom);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_TFile);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_TH1D);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__BHL6DictLN_TLorentzVector);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__BHL6DictLN_TMCgenBHL6),sizeof(TMCgenBHL6),-1,324864,"Monte Carlo generator",G__setup_memvarTMCgenBHL6,G__setup_memfuncTMCgenBHL6);
}
extern "C" void G__cpp_setupBHL6Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupBHL6Dict()");
  G__set_cpp_environmentBHL6Dict();
  G__cpp_setup_tagtableBHL6Dict();

  G__cpp_setup_inheritanceBHL6Dict();

  G__cpp_setup_typetableBHL6Dict();

  G__cpp_setup_memvarBHL6Dict();

  G__cpp_setup_memfuncBHL6Dict();
  G__cpp_setup_globalBHL6Dict();
  G__cpp_setup_funcBHL6Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncBHL6Dict();
  return;
}
class G__cpp_setup_initBHL6Dict {
  public:
    G__cpp_setup_initBHL6Dict() { G__add_setup_func("BHL6Dict",(G__incsetup)(&G__cpp_setupBHL6Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initBHL6Dict() { G__remove_setup_func("BHL6Dict"); }
};
G__cpp_setup_initBHL6Dict G__cpp_setup_initializerBHL6Dict;

