/********************************************************************
* BHL6Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BHL6Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableBHL6Dict();
extern void G__cpp_setup_inheritanceBHL6Dict();
extern void G__cpp_setup_typetableBHL6Dict();
extern void G__cpp_setup_memvarBHL6Dict();
extern void G__cpp_setup_globalBHL6Dict();
extern void G__cpp_setup_memfuncBHL6Dict();
extern void G__cpp_setup_funcBHL6Dict();
extern void G__set_cpp_environmentBHL6Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TMCgenBHL6.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BHL6DictLN_TClass;
extern G__linked_taginfo G__BHL6DictLN_TBuffer;
extern G__linked_taginfo G__BHL6DictLN_TMemberInspector;
extern G__linked_taginfo G__BHL6DictLN_TObject;
extern G__linked_taginfo G__BHL6DictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__BHL6DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__BHL6DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BHL6DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__BHL6DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BHL6DictLN_TRandom;
extern G__linked_taginfo G__BHL6DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__BHL6DictLN_TFile;
extern G__linked_taginfo G__BHL6DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__BHL6DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__BHL6DictLN_TH1D;
extern G__linked_taginfo G__BHL6DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__BHL6DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__BHL6DictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__BHL6DictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__BHL6DictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__BHL6DictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__BHL6DictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__BHL6DictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__BHL6DictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__BHL6DictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__BHL6DictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__BHL6DictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__BHL6DictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__BHL6DictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__BHL6DictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__BHL6DictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__BHL6DictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__BHL6DictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__BHL6DictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__BHL6DictLN_TLorentzVector;
extern G__linked_taginfo G__BHL6DictLN_TMCgenBHL6;

/* STUB derived class for protected member access */
