//
// File generated by /root/bin/rootcint at Wed Jan 29 18:30:10 2020

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME ProdDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "ProdDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void TRig_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TRig(void *p = 0);
   static void *newArray_TRig(Long_t size, void *p);
   static void delete_TRig(void *p);
   static void deleteArray_TRig(void *p);
   static void destruct_TRig(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::TRig*)
   {
      ::TRig *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TRig >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TRig", ::TRig::Class_Version(), "./TRig.h", 80,
                  typeid(::TRig), ::ROOT::DefineBehavior(ptr, ptr),
                  &::TRig::Dictionary, isa_proxy, 4,
                  sizeof(::TRig) );
      instance.SetNew(&new_TRig);
      instance.SetNewArray(&newArray_TRig);
      instance.SetDelete(&delete_TRig);
      instance.SetDeleteArray(&deleteArray_TRig);
      instance.SetDestructor(&destruct_TRig);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::TRig*)
   {
      return GenerateInitInstanceLocal((::TRig*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TRig*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

namespace ROOTDict {
   void TRobolProd_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TRobolProd(void *p = 0);
   static void *newArray_TRobolProd(Long_t size, void *p);
   static void delete_TRobolProd(void *p);
   static void deleteArray_TRobolProd(void *p);
   static void destruct_TRobolProd(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::TRobolProd*)
   {
      ::TRobolProd *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TRobolProd >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TRobolProd", ::TRobolProd::Class_Version(), "./TRobolProd.h", 26,
                  typeid(::TRobolProd), ::ROOT::DefineBehavior(ptr, ptr),
                  &::TRobolProd::Dictionary, isa_proxy, 4,
                  sizeof(::TRobolProd) );
      instance.SetNew(&new_TRobolProd);
      instance.SetNewArray(&newArray_TRobolProd);
      instance.SetDelete(&delete_TRobolProd);
      instance.SetDeleteArray(&deleteArray_TRobolProd);
      instance.SetDestructor(&destruct_TRobolProd);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::TRobolProd*)
   {
      return GenerateInitInstanceLocal((::TRobolProd*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TRobolProd*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

namespace ROOTDict {
   void TSemaf_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TSemaf(void *p = 0);
   static void *newArray_TSemaf(Long_t size, void *p);
   static void delete_TSemaf(void *p);
   static void deleteArray_TSemaf(void *p);
   static void destruct_TSemaf(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::TSemaf*)
   {
      ::TSemaf *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TSemaf >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TSemaf", ::TSemaf::Class_Version(), "./TSemaf.h", 21,
                  typeid(::TSemaf), ::ROOT::DefineBehavior(ptr, ptr),
                  &::TSemaf::Dictionary, isa_proxy, 4,
                  sizeof(::TSemaf) );
      instance.SetNew(&new_TSemaf);
      instance.SetNewArray(&newArray_TSemaf);
      instance.SetDelete(&delete_TSemaf);
      instance.SetDeleteArray(&deleteArray_TSemaf);
      instance.SetDestructor(&destruct_TSemaf);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::TSemaf*)
   {
      return GenerateInitInstanceLocal((::TSemaf*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TSemaf*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr TRig::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *TRig::Class_Name()
{
   return "TRig";
}

//______________________________________________________________________________
const char *TRig::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::TRig*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TRig::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::TRig*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TRig::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::TRig*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TRig::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::TRig*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
atomic_TClass_ptr TRobolProd::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *TRobolProd::Class_Name()
{
   return "TRobolProd";
}

//______________________________________________________________________________
const char *TRobolProd::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::TRobolProd*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TRobolProd::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::TRobolProd*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TRobolProd::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::TRobolProd*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TRobolProd::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::TRobolProd*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
atomic_TClass_ptr TSemaf::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *TSemaf::Class_Name()
{
   return "TSemaf";
}

//______________________________________________________________________________
const char *TSemaf::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::TSemaf*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TSemaf::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::TSemaf*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TSemaf::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::TSemaf*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TSemaf::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::TSemaf*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void TRobolProd::Streamer(TBuffer &R__b)
{
   // Stream an object of class TRobolProd.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(TRobolProd::Class(),this);
   } else {
      R__b.WriteClassBuffer(TRobolProd::Class(),this);
   }
}

//______________________________________________________________________________
void TRobolProd::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TRobolProd.
      TClass *R__cl = ::TRobolProd::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "f_Name[64]", f_Name);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "f_HistNormName", &f_HistNormName);
      R__insp.InspectMember(f_HistNormName, "f_HistNormName.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*f_RNgen", &f_RNgen);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*f_MCgen", &f_MCgen);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*f_TRigLib", &f_TRigLib);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*f_HstFile", &f_HstFile);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*f_GenFile", &f_GenFile);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*f_Out", &f_Out);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "f_TraceFile", (void*)&f_TraceFile);
      R__insp.InspectMember("ofstream", (void*)&f_TraceFile, "f_TraceFile.", true);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "f_NevGen", &f_NevGen);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "f_count1", &f_count1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "f_isNewRun", &f_isNewRun);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_NevGen", &m_NevGen);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_count1", &m_count1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_pi", &m_pi);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_NEVTOT", &m_NEVTOT);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_VMAXE", &m_VMAXE);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_NPHI", &m_NPHI);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_NTHE", &m_NTHE);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_TminF", &m_TminF);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_TmaxF", &m_TmaxF);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_dcone_calo1", &m_dcone_calo1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_th1n_calo2", &m_th1n_calo2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_th2n_calo2", &m_th2n_calo2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_th1w_calo2", &m_th1w_calo2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_th2w_calo2", &m_th2w_calo2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_dlth_calo2", &m_dlth_calo2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_dlph_calo2", &m_dlph_calo2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_y1A[4]", m_y1A);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_y1B[4]", m_y1B);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_y1C[4]", m_y1C);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_Z1[4]", m_Z1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_Z2[4]", m_Z2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_Z3[4]", m_Z3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_pbea1", &m_pbea1);
      R__insp.InspectMember(m_pbea1, "m_pbea1.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_pbea2", &m_pbea2);
      R__insp.InspectMember(m_pbea2, "m_pbea2.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_pfer1", &m_pfer1);
      R__insp.InspectMember(m_pfer1, "m_pfer1.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_pfer2", &m_pfer2);
      R__insp.InspectMember(m_pfer2, "m_pfer2.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_Nphot", &m_Nphot);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_phot[100]", m_phot);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hst_weight", &hst_weight);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hst_weight2", &hst_weight2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hst_wt2trig", &hst_wt2trig);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hst_Costhe", &hst_Costhe);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hst_v_bare1_ww", &hst_v_bare1_ww);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hst_v_bare1_nw", &hst_v_bare1_nw);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hst_v_bare1_nn", &hst_v_bare1_nn);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hst_v_calo2_ww", &hst_v_calo2_ww);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hst_v_calo2_nw", &hst_v_calo2_nw);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hst_v_calo2_nn", &hst_v_calo2_nn);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hst_v_sical2_ww", &hst_v_sical2_ww);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hst_v_sical2_nw", &hst_v_sical2_nw);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hst_v_sical2_nn", &hst_v_sical2_nn);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hst_trig_VP0", &hst_trig_VP0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hst_trig_VP1", &hst_trig_VP1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hst_trig_VP2", &hst_trig_VP2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hst_trig_VP3", &hst_trig_VP3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hst_trig_VP4", &hst_trig_VP4);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hst_trig_VP5", &hst_trig_VP5);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hst_trig_ZZ0", &hst_trig_ZZ0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hst_trig_ZZ1", &hst_trig_ZZ1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hst_trig_ZZ2", &hst_trig_ZZ2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hst_trig_ZZ3", &hst_trig_ZZ3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hst_trig_ZZ4", &hst_trig_ZZ4);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_TRobolProd(void *p) {
      return  p ? new(p) ::TRobolProd : new ::TRobolProd;
   }
   static void *newArray_TRobolProd(Long_t nElements, void *p) {
      return p ? new(p) ::TRobolProd[nElements] : new ::TRobolProd[nElements];
   }
   // Wrapper around operator delete
   static void delete_TRobolProd(void *p) {
      delete ((::TRobolProd*)p);
   }
   static void deleteArray_TRobolProd(void *p) {
      delete [] ((::TRobolProd*)p);
   }
   static void destruct_TRobolProd(void *p) {
      typedef ::TRobolProd current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::TRobolProd

//______________________________________________________________________________
void TSemaf::Streamer(TBuffer &R__b)
{
   // Stream an object of class TSemaf.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(TSemaf::Class(),this);
   } else {
      R__b.WriteClassBuffer(TSemaf::Class(),this);
   }
}

//______________________________________________________________________________
void TSemaf::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TSemaf.
      TClass *R__cl = ::TSemaf::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_flag", &m_flag);
      R__insp.InspectMember(m_flag, "m_flag.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_nevtot", &m_nevtot);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_nevent", &m_nevent);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_nevgrp", &m_nevgrp);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_TSemaf(void *p) {
      return  p ? new(p) ::TSemaf : new ::TSemaf;
   }
   static void *newArray_TSemaf(Long_t nElements, void *p) {
      return p ? new(p) ::TSemaf[nElements] : new ::TSemaf[nElements];
   }
   // Wrapper around operator delete
   static void delete_TSemaf(void *p) {
      delete ((::TSemaf*)p);
   }
   static void deleteArray_TSemaf(void *p) {
      delete [] ((::TSemaf*)p);
   }
   static void destruct_TSemaf(void *p) {
      typedef ::TSemaf current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::TSemaf

//______________________________________________________________________________
void TRig::Streamer(TBuffer &R__b)
{
   // Stream an object of class TRig.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(TRig::Class(),this);
   } else {
      R__b.WriteClassBuffer(TRig::Class(),this);
   }
}

//______________________________________________________________________________
void TRig::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TRig.
      TClass *R__cl = ::TRig::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "f_Name[64]", f_Name);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "f_Version", &f_Version);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "f_Date[40]", f_Date);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_CMSENE", &m_CMSENE);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_TRig(void *p) {
      return  p ? new(p) ::TRig : new ::TRig;
   }
   static void *newArray_TRig(Long_t nElements, void *p) {
      return p ? new(p) ::TRig[nElements] : new ::TRig[nElements];
   }
   // Wrapper around operator delete
   static void delete_TRig(void *p) {
      delete ((::TRig*)p);
   }
   static void deleteArray_TRig(void *p) {
      delete [] ((::TRig*)p);
   }
   static void destruct_TRig(void *p) {
      typedef ::TRig current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::TRig

/********************************************************
* ProdDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableProdDict();

extern "C" void G__set_cpp_environmentProdDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("TRobolProd.h");
  G__add_compiledheader("TSemaf.h");
  G__add_compiledheader("TRig.h");
  G__cpp_reset_tagtableProdDict();
}
#include <new>
extern "C" int G__cpp_dllrevProdDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TRig */
static int G__ProdDict_330_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TRig* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TRig[n];
     } else {
       p = new((void*) gvp) TRig[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TRig;
     } else {
       p = new((void*) gvp) TRig;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ProdDictLN_TRig));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_330_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TRig* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new TRig((const char*) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) TRig((const char*) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ProdDictLN_TRig));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_330_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TRig*) G__getstructoffset())->Initialize();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_330_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TRig*) G__getstructoffset())->PrintAng((const char*) G__int(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3])
, (double) G__double(libp->para[4]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_330_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TRig*) G__getstructoffset())->TriCal1(
*(double*) G__Doubleref(&libp->para[0]), *(double*) G__Doubleref(&libp->para[1])
, *(double*) G__Doubleref(&libp->para[2]), *(double*) G__Doubleref(&libp->para[3])
, *(double*) G__Doubleref(&libp->para[4]), *(double*) G__Doubleref(&libp->para[5])
, *(double*) G__Doubleref(&libp->para[6]), (double*) G__int(libp->para[7])
, (double*) G__int(libp->para[8]), (double*) G__int(libp->para[9]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_330_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TRig*) G__getstructoffset())->TriSic2w(
*(int*) G__Intref(&libp->para[0]), *(int*) G__Intref(&libp->para[1])
, *(double*) G__Doubleref(&libp->para[2]), *(double*) G__Doubleref(&libp->para[3])
, (double*) G__int(libp->para[4]), (double*) G__int(libp->para[5])
, (double*) G__int(libp->para[6]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_330_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TRig*) G__getstructoffset())->UniSical(*(int*) G__Intref(&libp->para[0]), *(int*) G__Intref(&libp->para[1])
, *(int*) G__Intref(&libp->para[2]), *(int*) G__Intref(&libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_330_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TRig*) G__getstructoffset())->UniElcal(*(int*) G__Intref(&libp->para[0]), *(int*) G__Intref(&libp->para[1])
, *(int*) G__Intref(&libp->para[2]), *(int*) G__Intref(&libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_330_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TRig*) G__getstructoffset())->SetTrisic2w();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_330_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TRig*) G__getstructoffset())->SetUniElcal();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_330_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TRig*) G__getstructoffset())->SetAleph93();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_330_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TRig*) G__getstructoffset())->TAleph93(*(int*) G__Intref(&libp->para[0]), *(int*) G__Intref(&libp->para[1])
, *(int*) G__Intref(&libp->para[2]), *(int*) G__Intref(&libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_330_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TRig*) G__getstructoffset())->TAleph94(*(int*) G__Intref(&libp->para[0]), *(int*) G__Intref(&libp->para[1])
, *(int*) G__Intref(&libp->para[2]), *(int*) G__Intref(&libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_330_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TRig*) G__getstructoffset())->TAleph95(*(int*) G__Intref(&libp->para[0]), *(int*) G__Intref(&libp->para[1])
, *(int*) G__Intref(&libp->para[2]), *(int*) G__Intref(&libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_330_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TRig*) G__getstructoffset())->TOpal93(*(int*) G__Intref(&libp->para[0]), *(int*) G__Intref(&libp->para[1])
, *(int*) G__Intref(&libp->para[2]), *(int*) G__Intref(&libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_330_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TRig*) G__getstructoffset())->TL3bgo2(*(int*) G__Intref(&libp->para[0]), *(int*) G__Intref(&libp->para[1])
, *(int*) G__Intref(&libp->para[2]), *(int*) G__Intref(&libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_330_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TRig*) G__getstructoffset())->TDelphi94(*(int*) G__Intref(&libp->para[0]), *(int*) G__Intref(&libp->para[1])
, *(int*) G__Intref(&libp->para[2]), *(int*) G__Intref(&libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_330_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TRig*) G__getstructoffset())->TAlephLcal(*(int*) G__Intref(&libp->para[0]), *(int*) G__Intref(&libp->para[1])
, *(int*) G__Intref(&libp->para[2]), *(int*) G__Intref(&libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_330_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TRig*) G__getstructoffset())->TOpalFcal(*(int*) G__Intref(&libp->para[0]), *(int*) G__Intref(&libp->para[1])
, *(int*) G__Intref(&libp->para[2]), *(int*) G__Intref(&libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_330_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TRig*) G__getstructoffset())->TL3bgo1(*(int*) G__Intref(&libp->para[0]), *(int*) G__Intref(&libp->para[1])
, *(int*) G__Intref(&libp->para[2]), *(int*) G__Intref(&libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_330_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TRig*) G__getstructoffset())->TDelphiSat(*(int*) G__Intref(&libp->para[0]), *(int*) G__Intref(&libp->para[1])
, *(int*) G__Intref(&libp->para[2]), *(int*) G__Intref(&libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_330_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TRig::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_330_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TRig::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_330_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TRig::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_330_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TRig::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_330_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TRig*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_330_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TRig::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_330_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TRig::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_330_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TRig::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_330_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TRig::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__ProdDict_330_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TRig* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TRig(*(TRig*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ProdDictLN_TRig));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TRig G__TTRig;
static int G__ProdDict_330_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TRig*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TRig*) (soff+(sizeof(TRig)*i)))->~G__TTRig();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TRig*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TRig*) (soff))->~G__TTRig();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__ProdDict_330_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TRig* dest = (TRig*) G__getstructoffset();
   *dest = *(TRig*) libp->para[0].ref;
   const TRig& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* TRobolProd */
static int G__ProdDict_338_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TRobolProd* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TRobolProd[n];
     } else {
       p = new((void*) gvp) TRobolProd[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TRobolProd;
     } else {
       p = new((void*) gvp) TRobolProd;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ProdDictLN_TRobolProd));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_338_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TRobolProd* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new TRobolProd((const char*) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) TRobolProd((const char*) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ProdDictLN_TRobolProd));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_338_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TRobolProd*) G__getstructoffset())->Initialize((ofstream*) G__int(libp->para[0]), (TFile*) G__int(libp->para[1])
, (TFile*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_338_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TRobolProd*) G__getstructoffset())->Hbooker();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_338_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TRobolProd*) G__getstructoffset())->Production(*(double*) G__Doubleref(&libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_338_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TRobolProd*) G__getstructoffset())->FillTrig92((TH1D*) G__int(libp->para[0]), (double) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_338_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TRobolProd*) G__getstructoffset())->FillTrig95((TH1D*) G__int(libp->para[0]), (double) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_338_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((TRobolProd*) G__getstructoffset())->TH1D_UP((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (double) G__double(libp->para[3])
, (double) G__double(libp->para[4])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_338_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((TRobolProd*) G__getstructoffset())->TH2D_UP(
(const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (double) G__double(libp->para[3])
, (double) G__double(libp->para[4]), (int) G__int(libp->para[5])
, (double) G__double(libp->para[6]), (double) G__double(libp->para[7])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_338_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TRobolProd*) G__getstructoffset())->sqr((const double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_338_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TRobolProd*) G__getstructoffset())->StopM((char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_338_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TRobolProd*) G__getstructoffset())->Finalize();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_338_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TRobolProd*) G__getstructoffset())->MomPrint(*(TLorentzVector*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_338_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TRobolProd::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_338_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TRobolProd::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_338_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TRobolProd::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_338_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TRobolProd::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_338_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TRobolProd*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_338_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TRobolProd::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_338_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TRobolProd::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_338_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TRobolProd::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_338_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TRobolProd::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TRobolProd G__TTRobolProd;
static int G__ProdDict_338_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TRobolProd*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TRobolProd*) (soff+(sizeof(TRobolProd)*i)))->~G__TTRobolProd();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TRobolProd*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TRobolProd*) (soff))->~G__TTRobolProd();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* TSemaf */
static int G__ProdDict_339_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TSemaf* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TSemaf[n];
     } else {
       p = new((void*) gvp) TSemaf[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TSemaf;
     } else {
       p = new((void*) gvp) TSemaf;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ProdDictLN_TSemaf));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_339_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TSemaf* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new TSemaf(*((TString*) G__int(libp->para[0])));
   } else {
     p = new((void*) gvp) TSemaf(*((TString*) G__int(libp->para[0])));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ProdDictLN_TSemaf));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_339_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TSemaf* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 2
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new TSemaf(*((TString*) G__int(libp->para[0])), (double) G__double(libp->para[1]));
   } else {
     p = new((void*) gvp) TSemaf(*((TString*) G__int(libp->para[0])), (double) G__double(libp->para[1]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ProdDictLN_TSemaf));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_339_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TSemaf* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 3
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new TSemaf(
*((TString*) G__int(libp->para[0])), (double) G__double(libp->para[1])
, (long) G__int(libp->para[2]));
   } else {
     p = new((void*) gvp) TSemaf(
*((TString*) G__int(libp->para[0])), (double) G__double(libp->para[1])
, (long) G__int(libp->para[2]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ProdDictLN_TSemaf));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_339_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TSemaf::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_339_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TSemaf::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_339_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TSemaf::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_339_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TSemaf::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_339_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TSemaf*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_339_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TSemaf::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_339_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TSemaf::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_339_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TSemaf::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ProdDict_339_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TSemaf::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__ProdDict_339_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TSemaf* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TSemaf(*(TSemaf*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ProdDictLN_TSemaf));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TSemaf G__TTSemaf;
static int G__ProdDict_339_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TSemaf*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TSemaf*) (soff+(sizeof(TSemaf)*i)))->~G__TTSemaf();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TSemaf*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TSemaf*) (soff))->~G__TTSemaf();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__ProdDict_339_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TSemaf* dest = (TSemaf*) G__getstructoffset();
   *dest = *(TSemaf*) libp->para[0].ref;
   const TSemaf& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TRig */

/* TRobolProd */

/* TSemaf */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncProdDict {
 public:
  G__Sizep2memfuncProdDict(): p(&G__Sizep2memfuncProdDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncProdDict::*p)();
};

size_t G__get_sizep2memfuncProdDict()
{
  G__Sizep2memfuncProdDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceProdDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__ProdDictLN_TRig))) {
     TRig *G__Lderived;
     G__Lderived=(TRig*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ProdDictLN_TRig),G__get_linked_tagnum(&G__ProdDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__ProdDictLN_TRobolProd))) {
     TRobolProd *G__Lderived;
     G__Lderived=(TRobolProd*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ProdDictLN_TRobolProd),G__get_linked_tagnum(&G__ProdDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__ProdDictLN_TSemaf))) {
     TSemaf *G__Lderived;
     G__Lderived=(TSemaf*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ProdDictLN_TSemaf),G__get_linked_tagnum(&G__ProdDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableProdDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__ProdDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ProdDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ProdDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ProdDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ProdDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__ProdDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ProdDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ProdDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ProdDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ProdDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__ProdDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__ProdDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__ProdDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__ProdDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__ProdDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__ProdDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__ProdDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__ProdDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__ProdDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__ProdDictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__ProdDictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__ProdDictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__ProdDictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__ProdDictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__ProdDictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__ProdDictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__ProdDictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__ProdDictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__ProdDictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__ProdDictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__ProdDictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__ProdDictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__ProdDictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__ProdDictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__ProdDictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__ProdDictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TRig */
static void G__setup_memvarTRig(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__ProdDictLN_TRig));
   { TRig *p; p=(TRig*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->f_Name)-(long)(p)),99,0,0,-1,-1,-1,1,"f_Name[64]=",0,"Name of a give instance of the class");
   G__memvar_setup((void*)((long)(&p->f_Version)-(long)(p)),102,0,0,-1,-1,-1,1,"f_Version=",0,"Actual VERSION of the program");
   G__memvar_setup((void*)((long)(&p->f_Date)-(long)(p)),99,0,0,-1,-1,-1,1,"f_Date[40]=",0,"Release DATE of the program");
   G__memvar_setup((void*)((long)(&p->m_CMSENE)-(long)(p)),100,0,0,-1,-1,-1,1,"m_CMSENE=",0,"not used");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* TRobolProd */
static void G__setup_memvarTRobolProd(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__ProdDictLN_TRobolProd));
   { TRobolProd *p; p=(TRobolProd*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->f_Name)-(long)(p)),99,0,0,-1,-1,-1,1,"f_Name[64]=",0,"Name of a give instance of the class");
   G__memvar_setup((void*)((long)(&p->f_HistNormName)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__ProdDictLN_TString),-1,-1,1,"f_HistNormName=",0,"name of the normalization histo");
   G__memvar_setup((void*)((long)(&p->f_RNgen)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TRandom),-1,-1,1,"f_RNgen=",0,"! Central RN event generator");
   G__memvar_setup((void*)((long)(&p->f_MCgen)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TMCgenBHL6),-1,-1,1,"f_MCgen=",0,"! MC event generator");
   G__memvar_setup((void*)((long)(&p->f_TRigLib)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TRig),-1,-1,1,"f_TRigLib=",0,"LEP trigger collection");
   G__memvar_setup((void*)((long)(&p->f_HstFile)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TFile),-1,-1,1,"f_HstFile=",0,"! ROOT DiskFile with all histos");
   G__memvar_setup((void*)((long)(&p->f_GenFile)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TFile),-1,-1,1,"f_GenFile=",0,"! ROOT DiskFile with MC generator");
   G__memvar_setup((void*)((long)(&p->f_Out)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ProdDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR),G__defined_typename("ofstream"),-1,1,"f_Out=",0,"! Central Logfile for messages");
   G__memvar_setup((void*)((long)(&p->f_TraceFile)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__ProdDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR),G__defined_typename("ofstream"),-1,1,"f_TraceFile=",0,"! Special DiskFile for debug");
   G__memvar_setup((void*)((long)(&p->f_NevGen)-(long)(p)),100,0,0,-1,-1,-1,1,"f_NevGen=",0,"event serial number");
   G__memvar_setup((void*)((long)(&p->f_count1)-(long)(p)),100,0,0,-1,-1,-1,1,"f_count1=",0,"auxiliary event counter (debug)");
   G__memvar_setup((void*)((long)(&p->f_isNewRun)-(long)(p)),108,0,0,-1,-1,-1,1,"f_isNewRun=",0,"\"is this new run?\"");
   G__memvar_setup((void*)((long)(&p->m_NevGen)-(long)(p)),108,0,0,-1,-1,-1,1,"m_NevGen=",0,"event serial number");
   G__memvar_setup((void*)((long)(&p->m_count1)-(long)(p)),108,0,0,-1,-1,-1,1,"m_count1=",0,"auxiliary event counter (debug)");
   G__memvar_setup((void*)((long)(&p->m_pi)-(long)(p)),100,0,0,-1,-1,-1,1,"m_pi=",0,"/");
   G__memvar_setup((void*)((long)(&p->m_NEVTOT)-(long)(p)),105,0,0,-1,-1,-1,1,"m_NEVTOT=",0,"= 84000000, total no. of MC events to generate");
   G__memvar_setup((void*)((long)(&p->m_VMAXE)-(long)(p)),100,0,0,-1,-1,-1,1,"m_VMAXE=",0,"VMAXE   v_max              trigger maximum v");
   G__memvar_setup((void*)((long)(&p->m_NPHI)-(long)(p)),105,0,0,-1,-1,-1,1,"m_NPHI=",0,"NPHI    no of phi   sectors, CALO2, SICAL2");
   G__memvar_setup((void*)((long)(&p->m_NTHE)-(long)(p)),105,0,0,-1,-1,-1,1,"m_NTHE=",0,"NTHE    no of theta sectors, CALO2, SICAL2");
   G__memvar_setup((void*)((long)(&p->m_TminF)-(long)(p)),100,0,0,-1,-1,-1,1,"m_TminF=",0,"TminW   fidutial theta_min wide, CALO2, SICAL2");
   G__memvar_setup((void*)((long)(&p->m_TmaxF)-(long)(p)),100,0,0,-1,-1,-1,1,"m_TmaxF=",0,"TmaxW   fidutial theta_max wide, CALO2, SICAL2");
   G__memvar_setup((void*)((long)(&p->m_dcone_calo1)-(long)(p)),100,0,0,-1,-1,-1,1,"m_dcone_calo1=",0,"CALO1");
   G__memvar_setup((void*)((long)(&p->m_th1n_calo2)-(long)(p)),100,0,0,-1,-1,-1,1,"m_th1n_calo2=",0,"CALO2");
   G__memvar_setup((void*)((long)(&p->m_th2n_calo2)-(long)(p)),100,0,0,-1,-1,-1,1,"m_th2n_calo2=",0,"CALO2");
   G__memvar_setup((void*)((long)(&p->m_th1w_calo2)-(long)(p)),100,0,0,-1,-1,-1,1,"m_th1w_calo2=",0,"CALO2");
   G__memvar_setup((void*)((long)(&p->m_th2w_calo2)-(long)(p)),100,0,0,-1,-1,-1,1,"m_th2w_calo2=",0,"CALO2");
   G__memvar_setup((void*)((long)(&p->m_dlth_calo2)-(long)(p)),100,0,0,-1,-1,-1,1,"m_dlth_calo2=",0,"CALO2");
   G__memvar_setup((void*)((long)(&p->m_dlph_calo2)-(long)(p)),100,0,0,-1,-1,-1,1,"m_dlph_calo2=",0,"CALO2");
   G__memvar_setup((void*)((long)(&p->m_y1A)-(long)(p)),100,0,0,-1,-1,-1,1,"m_y1A[4]=",0,"y of BARE1");
   G__memvar_setup((void*)((long)(&p->m_y1B)-(long)(p)),100,0,0,-1,-1,-1,1,"m_y1B[4]=",0,"y of CALO1");
   G__memvar_setup((void*)((long)(&p->m_y1C)-(long)(p)),100,0,0,-1,-1,-1,1,"m_y1C[4]=",0,"y of CALO2");
   G__memvar_setup((void*)((long)(&p->m_Z1)-(long)(p)),100,0,0,-1,-1,-1,1,"m_Z1[4]=",0,"z of SICAL2");
   G__memvar_setup((void*)((long)(&p->m_Z2)-(long)(p)),100,0,0,-1,-1,-1,1,"m_Z2[4]=",0,"z of SICAL2");
   G__memvar_setup((void*)((long)(&p->m_Z3)-(long)(p)),100,0,0,-1,-1,-1,1,"m_Z3[4]=",0,"z of SICAL2");
   G__memvar_setup((void*)((long)(&p->m_pbea1)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__ProdDictLN_TLorentzVector),-1,-1,1,"m_pbea1=",0,"! initial beams");
   G__memvar_setup((void*)((long)(&p->m_pbea2)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__ProdDictLN_TLorentzVector),-1,-1,1,"m_pbea2=",0,"! initial beams");
   G__memvar_setup((void*)((long)(&p->m_pfer1)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__ProdDictLN_TLorentzVector),-1,-1,1,"m_pfer1=",0,"! final fermions");
   G__memvar_setup((void*)((long)(&p->m_pfer2)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__ProdDictLN_TLorentzVector),-1,-1,1,"m_pfer2=",0,"! final fermions");
   G__memvar_setup((void*)((long)(&p->m_Nphot)-(long)(p)),105,0,0,-1,-1,-1,1,"m_Nphot=",0,"! photon multiplicity");
   G__memvar_setup((void*)((long)(&p->m_phot)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__ProdDictLN_TLorentzVector),-1,-1,1,"m_phot[100]=",0,"! photon 4-momenta");
   G__memvar_setup((void*)((long)(&p->hst_weight)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TH1D),-1,-1,1,"hst_weight=",0,"!  No streamer!!!");
   G__memvar_setup((void*)((long)(&p->hst_weight2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TH1D),-1,-1,1,"hst_weight2=",0,"!  No streamer!!!");
   G__memvar_setup((void*)((long)(&p->hst_wt2trig)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TH1D),-1,-1,1,"hst_wt2trig=",0,"!  No streamer!!!");
   G__memvar_setup((void*)((long)(&p->hst_Costhe)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TH1D),-1,-1,1,"hst_Costhe=",0,"!  No streamer!!!");
   G__memvar_setup((void*)((long)(&p->hst_v_bare1_ww)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TH1D),-1,-1,1,"hst_v_bare1_ww=",0,"!");
   G__memvar_setup((void*)((long)(&p->hst_v_bare1_nw)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TH1D),-1,-1,1,"hst_v_bare1_nw=",0,"!");
   G__memvar_setup((void*)((long)(&p->hst_v_bare1_nn)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TH1D),-1,-1,1,"hst_v_bare1_nn=",0,"!");
   G__memvar_setup((void*)((long)(&p->hst_v_calo2_ww)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TH1D),-1,-1,1,"hst_v_calo2_ww=",0,"!");
   G__memvar_setup((void*)((long)(&p->hst_v_calo2_nw)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TH1D),-1,-1,1,"hst_v_calo2_nw=",0,"!");
   G__memvar_setup((void*)((long)(&p->hst_v_calo2_nn)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TH1D),-1,-1,1,"hst_v_calo2_nn=",0,"!");
   G__memvar_setup((void*)((long)(&p->hst_v_sical2_ww)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TH1D),-1,-1,1,"hst_v_sical2_ww=",0,"!");
   G__memvar_setup((void*)((long)(&p->hst_v_sical2_nw)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TH1D),-1,-1,1,"hst_v_sical2_nw=",0,"!");
   G__memvar_setup((void*)((long)(&p->hst_v_sical2_nn)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TH1D),-1,-1,1,"hst_v_sical2_nn=",0,"!");
   G__memvar_setup((void*)((long)(&p->hst_trig_VP0)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TH1D),-1,-1,1,"hst_trig_VP0=",0,"!");
   G__memvar_setup((void*)((long)(&p->hst_trig_VP1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TH1D),-1,-1,1,"hst_trig_VP1=",0,"!");
   G__memvar_setup((void*)((long)(&p->hst_trig_VP2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TH1D),-1,-1,1,"hst_trig_VP2=",0,"!");
   G__memvar_setup((void*)((long)(&p->hst_trig_VP3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TH1D),-1,-1,1,"hst_trig_VP3=",0,"!");
   G__memvar_setup((void*)((long)(&p->hst_trig_VP4)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TH1D),-1,-1,1,"hst_trig_VP4=",0,"!");
   G__memvar_setup((void*)((long)(&p->hst_trig_VP5)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TH1D),-1,-1,1,"hst_trig_VP5=",0,"!");
   G__memvar_setup((void*)((long)(&p->hst_trig_ZZ0)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TH1D),-1,-1,1,"hst_trig_ZZ0=",0,"!");
   G__memvar_setup((void*)((long)(&p->hst_trig_ZZ1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TH1D),-1,-1,1,"hst_trig_ZZ1=",0,"!");
   G__memvar_setup((void*)((long)(&p->hst_trig_ZZ2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TH1D),-1,-1,1,"hst_trig_ZZ2=",0,"!");
   G__memvar_setup((void*)((long)(&p->hst_trig_ZZ3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TH1D),-1,-1,1,"hst_trig_ZZ3=",0,"!");
   G__memvar_setup((void*)((long)(&p->hst_trig_ZZ4)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TH1D),-1,-1,1,"hst_trig_ZZ4=",0,"!");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* TSemaf */
static void G__setup_memvarTSemaf(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__ProdDictLN_TSemaf));
   { TSemaf *p; p=(TSemaf*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->m_flag)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__ProdDictLN_TString),-1,-1,1,"m_flag=",0,"flag = \"CONTINUE\",\"START\",\"STOP\"");
   G__memvar_setup((void*)((long)(&p->m_nevtot)-(long)(p)),100,0,0,-1,-1,-1,1,"m_nevtot=",0,"no. of MC events to be generated");
   G__memvar_setup((void*)((long)(&p->m_nevent)-(long)(p)),100,0,0,-1,-1,-1,1,"m_nevent=",0,"no. of MC events to be generated");
   G__memvar_setup((void*)((long)(&p->m_nevgrp)-(long)(p)),108,0,0,-1,-1,-1,1,"m_nevgrp=",0,"no. of groups of MC events");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ProdDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarProdDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTRig(void) {
   /* TRig */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__ProdDictLN_TRig));
   G__memfunc_setup("TRig",374,G__ProdDict_330_0_1, 105, G__get_linked_tagnum(&G__ProdDictLN_TRig), -1, 0, 0, 1, 1, 0, "", "explicit default constructor for streamer", (void*) NULL, 0);
   G__memfunc_setup("TRig",374,G__ProdDict_330_0_2, 105, G__get_linked_tagnum(&G__ProdDictLN_TRig), -1, 0, 1, 1, 1, 0, "C - - 10 - -", "user constructor", (void*) NULL, 0);
   G__memfunc_setup("Initialize",1042,G__ProdDict_330_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintAng",803,G__ProdDict_330_0_4, 121, -1, -1, 0, 5, 1, 1, 0, 
"C - - 10 - name d - - 0 - th1w "
"d - - 0 - th2w d - - 0 - th1n "
"d - - 0 - th2n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TriCal1",624,G__ProdDict_330_0_5, 121, -1, -1, 0, 10, 1, 1, 0, 
"d - - 1 - th1n d - - 1 - th2n "
"d - - 1 - th1w d - - 1 - th2w "
"d - - 1 - dcone d - - 1 - dlth "
"d - - 1 - dlph D - - 0 - y1A "
"D - - 0 - y1B D - - 0 - y1C", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TriSic2w",759,G__ProdDict_330_0_6, 121, -1, -1, 0, 7, 1, 1, 0, 
"i - - 1 - Nphi i - - 1 - Nthe "
"d - - 1 - Tmind d - - 1 - Tmaxd "
"D - - 0 - Z1 D - - 0 - Z2 "
"D - - 0 - Z3", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UniSical",792,G__ProdDict_330_0_7, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - - 1 - lWW i - - 1 - lNN "
"i - - 1 - lNW i - - 1 - lWN", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UniElcal",781,G__ProdDict_330_0_8, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - - 1 - lWW i - - 1 - lNN "
"i - - 1 - lNW i - - 1 - lWN", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTrisic2w",1091,G__ProdDict_330_0_9, 121, -1, -1, 0, 0, 1, 1, 0, "", "SetTrisic2w", (void*) NULL, 0);
   G__memfunc_setup("SetUniElcal",1081,G__ProdDict_330_0_10, 121, -1, -1, 0, 0, 1, 1, 0, "", "SetUniElcal", (void*) NULL, 0);
   G__memfunc_setup("SetAleph93",898,G__ProdDict_330_0_11, 121, -1, -1, 0, 0, 1, 1, 0, "", "SetAleph93", (void*) NULL, 0);
   G__memfunc_setup("TAleph93",682,G__ProdDict_330_0_12, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - - 1 - lWW i - - 1 - lNN "
"i - - 1 - lNW i - - 1 - lWN", "TAleph93", (void*) NULL, 0);
   G__memfunc_setup("TAleph94",683,G__ProdDict_330_0_13, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - - 1 - lWW i - - 1 - lNN "
"i - - 1 - lNW i - - 1 - lWN", "TAleph94", (void*) NULL, 0);
   G__memfunc_setup("TAleph95",684,G__ProdDict_330_0_14, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - - 1 - lWW i - - 1 - lNN "
"i - - 1 - lNW i - - 1 - lWN", "TAleph95", (void*) NULL, 0);
   G__memfunc_setup("TOpal93",588,G__ProdDict_330_0_15, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - - 1 - lWW i - - 1 - lNN "
"i - - 1 - lNW i - - 1 - lWN", "TOpal93", (void*) NULL, 0);
   G__memfunc_setup("TL3bgo2",573,G__ProdDict_330_0_16, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - - 1 - lWW i - - 1 - lNN "
"i - - 1 - lNW i - - 1 - lWN", "TL3bgo2()", (void*) NULL, 0);
   G__memfunc_setup("TDelphi94",791,G__ProdDict_330_0_17, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - - 1 - lWW i - - 1 - lNN "
"i - - 1 - lNW i - - 1 - lWN", "TDelphi94()", (void*) NULL, 0);
   G__memfunc_setup("TAlephLcal",954,G__ProdDict_330_0_18, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - - 1 - lWW i - - 1 - lNN "
"i - - 1 - lNW i - - 1 - lWN", "TAlephLcal", (void*) NULL, 0);
   G__memfunc_setup("TOpalFcal",854,G__ProdDict_330_0_19, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - - 1 - lWW i - - 1 - lNN "
"i - - 1 - lNW i - - 1 - lWN", "TOpalFcal()", (void*) NULL, 0);
   G__memfunc_setup("TL3bgo1",572,G__ProdDict_330_0_20, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - - 1 - lWW i - - 1 - lNN "
"i - - 1 - lNW i - - 1 - lWN", "TL3bgo1()", (void*) NULL, 0);
   G__memfunc_setup("TDelphiSat",978,G__ProdDict_330_0_21, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - - 1 - lWW i - - 1 - lNN "
"i - - 1 - lNW i - - 1 - lWN", "TDelhiSat()", (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__ProdDict_330_0_22, 85, G__get_linked_tagnum(&G__ProdDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TRig::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__ProdDict_330_0_23, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TRig::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__ProdDict_330_0_24, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TRig::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__ProdDict_330_0_25, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TRig::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__ProdDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__ProdDict_330_0_29, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__ProdDict_330_0_30, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TRig::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__ProdDict_330_0_31, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TRig::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__ProdDict_330_0_32, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TRig::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__ProdDict_330_0_33, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TRig::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TRig", 374, G__ProdDict_330_0_34, (int) ('i'), G__get_linked_tagnum(&G__ProdDictLN_TRig), -1, 0, 1, 1, 1, 0, "u 'TRig' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TRig", 500, G__ProdDict_330_0_35, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__ProdDict_330_0_36, (int) ('u'), G__get_linked_tagnum(&G__ProdDictLN_TRig), -1, 1, 1, 1, 1, 0, "u 'TRig' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncTRobolProd(void) {
   /* TRobolProd */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__ProdDictLN_TRobolProd));
   G__memfunc_setup("TRobolProd",999,G__ProdDict_338_0_1, 105, G__get_linked_tagnum(&G__ProdDictLN_TRobolProd), -1, 0, 0, 1, 1, 0, "", "explicit default constructor for streamer", (void*) NULL, 0);
   G__memfunc_setup("TRobolProd",999,G__ProdDict_338_0_2, 105, G__get_linked_tagnum(&G__ProdDictLN_TRobolProd), -1, 0, 1, 1, 1, 0, "C - - 10 - -", "user constructor", (void*) NULL, 0);
   G__memfunc_setup("Initialize",1042,G__ProdDict_338_0_3, 121, -1, -1, 0, 3, 1, 1, 0, 
"U 'basic_ofstream<char,char_traits<char> >' 'ofstream' 0 - - U 'TFile' - 0 - - "
"U 'TFile' - 0 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Hbooker",714,G__ProdDict_338_0_4, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Production",1063,G__ProdDict_338_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("FillTrig92",904,G__ProdDict_338_0_6, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'TH1D' - 0 - hst_trig d - - 0 - WtMain", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FillTrig95",907,G__ProdDict_338_0_7, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'TH1D' - 0 - hst_trig d - - 0 - WtMain", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TH1D_UP",533,G__ProdDict_338_0_8, 85, G__get_linked_tagnum(&G__ProdDictLN_TH1D), -1, 0, 5, 1, 1, 0, 
"C - - 10 - - C - - 10 - - "
"i - - 0 - - d - - 0 - - "
"d - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TH2D_UP",534,G__ProdDict_338_0_9, 85, G__get_linked_tagnum(&G__ProdDictLN_TH2D), -1, 0, 8, 1, 1, 0, 
"C - - 10 - - C - - 10 - - "
"i - - 0 - - d - - 0 - - "
"d - - 0 - - i - - 0 - - "
"d - - 0 - - d - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("sqr",342,G__ProdDict_338_0_10, 100, -1, -1, 0, 1, 1, 1, 0, "d - - 10 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("StopM",499,G__ProdDict_338_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 0 - message", "Error message", (void*) NULL, 0);
   G__memfunc_setup("Finalize",818,G__ProdDict_338_0_12, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MomPrint",822,G__ProdDict_338_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TLorentzVector' - 1 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__ProdDict_338_0_14, 85, G__get_linked_tagnum(&G__ProdDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TRobolProd::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__ProdDict_338_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TRobolProd::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__ProdDict_338_0_16, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TRobolProd::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__ProdDict_338_0_17, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TRobolProd::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__ProdDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__ProdDict_338_0_21, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__ProdDict_338_0_22, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TRobolProd::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__ProdDict_338_0_23, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TRobolProd::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__ProdDict_338_0_24, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TRobolProd::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__ProdDict_338_0_25, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TRobolProd::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~TRobolProd", 1125, G__ProdDict_338_0_26, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncTSemaf(void) {
   /* TSemaf */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__ProdDictLN_TSemaf));
   G__memfunc_setup("TSemaf",576,G__ProdDict_339_0_1, 105, G__get_linked_tagnum(&G__ProdDictLN_TSemaf), -1, 0, 0, 1, 1, 0, "", "only for streamer", (void*) NULL, 0);
   G__memfunc_setup("TSemaf",576,G__ProdDict_339_0_2, 105, G__get_linked_tagnum(&G__ProdDictLN_TSemaf), -1, 0, 1, 1, 1, 0, "u 'TString' - 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TSemaf",576,G__ProdDict_339_0_3, 105, G__get_linked_tagnum(&G__ProdDictLN_TSemaf), -1, 0, 2, 1, 1, 0, 
"u 'TString' - 0 - flag d - - 0 - nevtot", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TSemaf",576,G__ProdDict_339_0_4, 105, G__get_linked_tagnum(&G__ProdDictLN_TSemaf), -1, 0, 3, 1, 1, 0, 
"u 'TString' - 0 - flag d - - 0 - nevtot "
"l - - 0 - nevgrp", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__ProdDict_339_0_5, 85, G__get_linked_tagnum(&G__ProdDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TSemaf::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__ProdDict_339_0_6, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TSemaf::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__ProdDict_339_0_7, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TSemaf::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__ProdDict_339_0_8, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TSemaf::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__ProdDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__ProdDict_339_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__ProdDict_339_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TSemaf::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__ProdDict_339_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TSemaf::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__ProdDict_339_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TSemaf::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__ProdDict_339_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TSemaf::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TSemaf", 576, G__ProdDict_339_0_17, (int) ('i'), G__get_linked_tagnum(&G__ProdDictLN_TSemaf), -1, 0, 1, 1, 1, 0, "u 'TSemaf' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TSemaf", 702, G__ProdDict_339_0_18, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__ProdDict_339_0_19, (int) ('u'), G__get_linked_tagnum(&G__ProdDictLN_TSemaf), -1, 1, 1, 1, 1, 0, "u 'TSemaf' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncProdDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalProdDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcProdDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__ProdDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR = { "basic_ofstream<char,char_traits<char> >" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TRandom = { "TRandom" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__ProdDictLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TH1D = { "TH1D" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TLorentzVector = { "TLorentzVector" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TMCgenBHL6 = { "TMCgenBHL6" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TRig = { "TRig" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TH2D = { "TH2D" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TRobolProd = { "TRobolProd" , 99 , -1 };
G__linked_taginfo G__ProdDictLN_TSemaf = { "TSemaf" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableProdDict() {
  G__ProdDictLN_TClass.tagnum = -1 ;
  G__ProdDictLN_TBuffer.tagnum = -1 ;
  G__ProdDictLN_TMemberInspector.tagnum = -1 ;
  G__ProdDictLN_TObject.tagnum = -1 ;
  G__ProdDictLN_TString.tagnum = -1 ;
  G__ProdDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR.tagnum = -1 ;
  G__ProdDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__ProdDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ProdDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__ProdDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ProdDictLN_TRandom.tagnum = -1 ;
  G__ProdDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__ProdDictLN_TFile.tagnum = -1 ;
  G__ProdDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__ProdDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__ProdDictLN_TH1D.tagnum = -1 ;
  G__ProdDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__ProdDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__ProdDictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__ProdDictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__ProdDictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__ProdDictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__ProdDictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__ProdDictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__ProdDictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__ProdDictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__ProdDictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__ProdDictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__ProdDictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__ProdDictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__ProdDictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__ProdDictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__ProdDictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__ProdDictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__ProdDictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__ProdDictLN_TLorentzVector.tagnum = -1 ;
  G__ProdDictLN_TMCgenBHL6.tagnum = -1 ;
  G__ProdDictLN_TRig.tagnum = -1 ;
  G__ProdDictLN_TH2D.tagnum = -1 ;
  G__ProdDictLN_TRobolProd.tagnum = -1 ;
  G__ProdDictLN_TSemaf.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableProdDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TString);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TRandom);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TFile);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TH1D);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TLorentzVector);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TMCgenBHL6);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__ProdDictLN_TRig),sizeof(TRig),-1,324864,(char*)NULL,G__setup_memvarTRig,G__setup_memfuncTRig);
   G__get_linked_tagnum_fwd(&G__ProdDictLN_TH2D);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__ProdDictLN_TRobolProd),sizeof(TRobolProd),-1,324864,(char*)NULL,G__setup_memvarTRobolProd,G__setup_memfuncTRobolProd);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__ProdDictLN_TSemaf),sizeof(TSemaf),-1,324864,(char*)NULL,G__setup_memvarTSemaf,G__setup_memfuncTSemaf);
}
extern "C" void G__cpp_setupProdDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupProdDict()");
  G__set_cpp_environmentProdDict();
  G__cpp_setup_tagtableProdDict();

  G__cpp_setup_inheritanceProdDict();

  G__cpp_setup_typetableProdDict();

  G__cpp_setup_memvarProdDict();

  G__cpp_setup_memfuncProdDict();
  G__cpp_setup_globalProdDict();
  G__cpp_setup_funcProdDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncProdDict();
  return;
}
class G__cpp_setup_initProdDict {
  public:
    G__cpp_setup_initProdDict() { G__add_setup_func("ProdDict",(G__incsetup)(&G__cpp_setupProdDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initProdDict() { G__remove_setup_func("ProdDict"); }
};
G__cpp_setup_initProdDict G__cpp_setup_initializerProdDict;

