/********************************************************************
* ProdDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ProdDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableProdDict();
extern void G__cpp_setup_inheritanceProdDict();
extern void G__cpp_setup_typetableProdDict();
extern void G__cpp_setup_memvarProdDict();
extern void G__cpp_setup_globalProdDict();
extern void G__cpp_setup_memfuncProdDict();
extern void G__cpp_setup_funcProdDict();
extern void G__set_cpp_environmentProdDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TRobolProd.h"
#include "TSemaf.h"
#include "TRig.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ProdDictLN_TClass;
extern G__linked_taginfo G__ProdDictLN_TBuffer;
extern G__linked_taginfo G__ProdDictLN_TMemberInspector;
extern G__linked_taginfo G__ProdDictLN_TObject;
extern G__linked_taginfo G__ProdDictLN_TString;
extern G__linked_taginfo G__ProdDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__ProdDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ProdDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ProdDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ProdDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ProdDictLN_TRandom;
extern G__linked_taginfo G__ProdDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__ProdDictLN_TFile;
extern G__linked_taginfo G__ProdDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__ProdDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__ProdDictLN_TH1D;
extern G__linked_taginfo G__ProdDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__ProdDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__ProdDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__ProdDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__ProdDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__ProdDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__ProdDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__ProdDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__ProdDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__ProdDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__ProdDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__ProdDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__ProdDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__ProdDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__ProdDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__ProdDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__ProdDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__ProdDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__ProdDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__ProdDictLN_TLorentzVector;
extern G__linked_taginfo G__ProdDictLN_TMCgenBHL6;
extern G__linked_taginfo G__ProdDictLN_TRig;
extern G__linked_taginfo G__ProdDictLN_TH2D;
extern G__linked_taginfo G__ProdDictLN_TRobolProd;
extern G__linked_taginfo G__ProdDictLN_TSemaf;

/* STUB derived class for protected member access */
